### ISSUE TITLE
rucio_daily.py error due to wrong default date 

### ISSUE THREAD

**Issue by kyrylogy** [dmwm/CMSSpark#120]
Running `cron4rucio_daily.sh` in k8s produces the following:
`Input Arguments: fdate:2022-09-21 00:00:00`, which gives an error, because date must be simply `2022-09-21`

The source of this problem lies [here](https://github.com/dmwm/CMSSpark/blob/bd49b3a6bca8f523fa0a3dd316b008c19945c0b7/src/python/CMSSpark/rucio_daily.py#L69), and it might be a bug of click library.
```
_VALID_DATE_FORMATS = ["%Y-%m-%d"]
@click.option("--fdate", required=False, default=date.today().strftime("%Y-%m-%d"),
              type=click.DateTime(_VALID_DATE_FORMATS) ... )
```
Output becomes `%Y-%m-%d %H-%M-%S`
It could be fixed by removing `type` parameter, as we don't use datetime object in that function. 

[click.DateTime documentation](https://click.palletsprojects.com/en/8.1.x/api/?highlight=datetime#click.DateTime)

**Comment by mrceyhun** [comment]
@kyrylogy I don't think it is because of Click. See [here](https://github.com/dmwm/CMSSpark/blob/master/bin/cron4rucio_daily.sh#L74), we provide `fdate` argument in the cron script, so that wrong date is not coming from Click's default date. Let me check and fix.
