### ISSUE TITLE
--cvmfs option to run_spark de facto mandatory

### ISSUE THREAD

**Issue by sciaba** [dmwm/CMSSpark#16]
To my understanding, run_spark cannot possibly run correctly from lxplus7 if the --cvmfs option is not used. 
This because the correct scripts are sourced, and the right options to spark_submit are used, only when --cvmfs is used.
I would recommend to either make it clear in the documentation or execute the commands needed from lxplus7 irrespective of the presence of --cvmfs.

**Comment by vkuznet** [comment]
Andrea, could you please try out head version (commit f88373c4788befdf9e2be8eb6a96bb31612bcee7 should fix the issues you pointed out).

**Comment by sciaba** [comment]
Hi Valentin, the fix works fine, thank you.
