### ISSUE TITLE
Reading Avro files as Dataframes instead of RDD?

### ISSUE THREAD

**Issue by sciaba** [dmwm/CMSSpark#17]
Hi,
would it be a good idea to modernize the code by reading Avro files as dataframes instead of RDD?
Look for example at https://github.com/databricks/spark-avro: it is enough to use

--packages com.databricks:spark-avro_2.11:4.0.0

to be able to use

df = spark.read.format("com.databricks.spark.avro").load(file)

So one could completely bypass the creation of an RDD which is then converted to a dataframe (this is my understanding at least).

**Comment by vkuznet** [comment]
Andrea,
I doubt it will work in generic case. The data we read may not fall into flat
format, e.g. the data may be nested, and therefore RDD is more generic.
I'm not against the suggested change but rather saying that it will require
long validation of all data sources we use. In particular the WMArchive
schema is very nested and has list, dicts data-structures.
Best,
Valentin.

**Comment by sciaba** [comment]
Understood. You can close the issue if you like.
Cheers,
Andrea

**Comment by nsmith-** [comment]
@sciaba @vkuznet the spark DataFrame objects fully support nested structure.  I can easily descend nested data with this method.

**Comment by vkuznet** [comment]
We just upgraded a week ago our production nodes from Spark 1.6 to Spark 2.X. In former we haven't not had such privilege and therefore kept code using RDD. With such change yes we can start talking about moving code forward. Feel free to create PRs against WMArchive codebase which requires reading Avro files.

**Comment by vkuznet** [comment]
And, we need code for CMSSpark to tests against all available Avro data-sources, if I recall correctly they are:
- cmssw, hdfs:///project/awg/cms/cmssw-popularity/avro-snappy
- jobmonitoring, hdfs:///project/awg/cms/jm-data-popularity/avro-snappy
- wmarchive, hdfs:///cms/wmarchive/avro
