### ISSUE TITLE
Make run_spark compatible with the ithdp-client cluster

### ISSUE THREAD

**Issue by sciaba** [dmwm/CMSSpark#18]
Hi,
when the user is logged to ithdp-client, the correct way to setup the environment is to do

source hadoop-setconf.sh analytix

I propose to modify run_spark in such a way that, if it is run from ithdp-client, this source command is executed, instead of the ones done for lxplus7.

**Comment by vkuznet** [comment]
Fixed in d62ae2f..baf61c1 commit
