### ISSUE TITLE
Wrong type

### ISSUE THREAD

**Issue by sciaba** [dmwm/CMSSpark#19]
In

https://github.com/dmwm/CMSSpark/blob/master/src/python/CMSSpark/schemas.py#L343

there should be StringType and not LongType.

**Comment by vkuznet** [comment]
Did you check that it is consistent from cmssw docs from different period of time, e.g. 2017 and 2018?

**Comment by sciaba** [comment]
No, I did not. Surely the change is needed for recent data. Besides, without the change, there is an illogical asymmetry in types, because the type for START_TIME is not the same as for END_TIME.

**Comment by vkuznet** [comment]
You're right. I fixed the problem.

**Comment by vkuznet** [comment]
Fixed: https://github.com/dmwm/CMSSpark/commit/8c765ef193e50a3df2dff03b06a4d11bb4949d77
