### ISSUE TITLE
dbs_events script missing header row in output

### ISSUE THREAD

**Issue by davidlange6** [dmwm/CMSSpark#22]
Hi @vkuznet 
I don't see the problem with a quick read through the code .. but the output (on vocms092) of the dbs_events script lacks its header row (/data/cms/pop-data/dbs_events.csv.gz). I noticed as my script depends on this header row.

**Comment by vkuznet** [comment]
Fixed, the error occurred after migration from Spark 1.X to Spark 2.X since hadoop output file names part-XXXXX have changed to part-XXXX-hash.csv New data-frame is already generated and contains headers.

**Comment by davidlange6** [comment]
Thanks - looks good to me now.
